export const REQUEST_NEWS = "REQUEST_NEWS";
export const RECEIVE_NEWS = "RECEIVE_NEWS";
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const FETCH_SCRAPE_NEW = "FETCH_SCRAPE_NEW";
export const ERROR_OCCURED = "ERROR_OCCURED";

