export const REQUEST_HEADLINES = "REQUEST_HEADLINES";
export const RECEIVE_HEADLINES = "RECEIVE_HEADLINES";
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";

